### ISSUE TITLE
The sum C

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/no_term#1]
Che succede se il file non esiste?

**Comment by CarloRuzzon** [comment]
Appunto prof, nulla, e non capisco come usare la condizione nell'if...

**Comment by FabioZTessitore** [comment]
ancora problemi?

**Comment by FabioZTessitore** [comment]
ci vuole tempo?

**Comment by CarloRuzzon** [comment]
Prof io sto facendo le 'ncurses, nelle stringhe per la compilazione avete
fatto un errore, ve l'ho scritto subito altrimenti mi scordavo

2017-02-18 10:29 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
L'ho visto. Correggo il prima possibile. Grazie e bravo

Il 19 feb 2017 10:11 AM, "CarloRuzzon" <notifications@github.com> ha
scritto:
